#!/bin/bash
sudo echo "🔄 Updating system with pacman..."
sudo pacman -Syu 

echo -e "\n🚀 Updating AUR packages with yay..."
yay -Syu 

echo -e "\n📦 Updating flatpak packages..."
flatpak update --assumeyes

echo -e "\n🗑️ Removing orphaned packages..."
orphans=$(pacman -Qdtq 2>/dev/null)
if [ -n "$orphans" ]; then
    sudo pacman -Rns $orphans
else
    echo "✅ No orphaned packages found."
fi

echo -e "\n🧽 Cleaning unused flatpak runtimes..."
flatpak uninstall --unused --assumeyes

sudo rm -rf /tmp/*
sudo rm -rf /var/tmp/*



echo -e "\n🎉 System update and cleanup complete!"
